name: Build APK

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to load in the WebView'
        required: true
        default: 'https://example.com'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        java-package: jdk
        architecture: x64
        check-latest: false
    
    - name: Make gradlew executable (Windows specific)
      run: |
        chmod +x gradlew  # Ensures gradlew is executable
        if ($IsWindows) { Set-ExecutionPolicy RemoteSigned -Scope Process }  # For Windows PowerShell if needed
    
    - name: Build APK
      run: |
        cd app  # Update this if needed based on repo structure
        sed -i "s|PLACEHOLDER_URL|${{ github.event.inputs.url }}|g" app/src/main/java/com/example/myapp/MainActivity.java  # Correct path
        ./gradlew.bat assembleRelease  # Use gradlew.bat for Windows
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk  # Ensure this path is correct
