name: Build APK

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to load in the WebView'
        required: true
        default: 'https://example.com'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: List directory structure
      run: ls -R  # Helps you verify the folder structure
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        java-package: jdk
        architecture: x64
        check-latest: false
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN
        overwrite-settings: true
        job-status: success
    
    - name: Make gradlew executable
      run: chmod +x gradlew
    
    - name: Build APK
      run: |
        cd myapp/android-app  # Update path here
        sed -i "s|PLACEHOLDER_URL|${{ github.event.inputs.url }}|g" app/src/main/java/com/example/myapp/MainActivity.java
        ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: myapp/android-app/app/release/app-release.apk  # Update path
