name: Build APK

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to load in the WebView'
        required: true
        default: 'https://example.com'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        java-package: jdk
        architecture: x64
        check-latest: false
    
    - name: Make gradlew executable
      run: chmod +x gradlew  # Ensures gradlew is executable on Linux

    - name: Build APK
      run: |
        cd app  # Update path if needed
        # Check if the file exists before applying the sed command
        if [ -f "app/src/main/java/com/example/myapp/MainActivity.java" ]; then
          sed -i "s|PLACEHOLDER_URL|${{ github.event.inputs.url }}|g" app/src/main/java/com/example/myapp/MainActivity.java
        else
          echo "MainActivity.java not found, skipping URL replacement."
        fi
        ./gradlew assembleRelease  # Use gradlew script on Ubuntu
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk  # Ensure path is correct
