name: Build APK

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to load in the WebView'
        required: true
        default: 'https://example.com'

jobs:
  build:
    runs-on: windows-latest  # Use Windows OS
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'  # JDK distribution
    
    - name: Make gradlew executable
      run: |
        icacls gradlew /grant Everyone:F
    
    - name: Build APK
      run: |
        cd android-app
        sed -i "s|PLACEHOLDER_URL|${{ github.event.inputs.url }}|g" app/src/main/java/com/example/myapp/MainActivity.java
        ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: android-app/app/build/outputs/apk/release/app-release.apk
