name: Build Signed APK

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to load in the WebView'
        required: true
        default: 'https://example.com'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Ensure gradlew is executable
      run: |
        if [ -f "./gradlew" ]; then
          chmod +x gradlew
        else
          echo "gradlew not found!"
          exit 1
        fi

    - name: Replace URL in MainActivity
      run: |
        cd app/src/main/java/com/example/myapp
        if [ -f "MainActivity.java" ]; then
          sed -i "s|PLACEHOLDER_URL|${{ github.event.inputs.url }}|g" MainActivity.java
        else
          echo "MainActivity.java not found!"
          exit 1
        fi
        cd ../../../../../../../

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Sign APK
      run: |
        key_alias=${{ secrets.KEY_ALIAS }}
        key_password=${{ secrets.KEY_PASSWORD }}
        keystore_path=webview.jks
        store_password=${{ secrets.KEYSTORE_PASSWORD }}

        ./gradlew signingReport
        ./gradlew assembleRelease -Pandroid.injected.signing.store.file=${{ secrets.KEYSTORE_PATH }} -Pandroid.injected.signing.key.alias=$key_alias -Pandroid.injected.signing.store.password=$store_password -Pandroid.injected.signing.key.password=$key_password

    - name: Upload Signed APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Output download URL
      run: |
        echo "Download URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
