name: Build APK

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'The URL to load in the WebView'
        required: true
        default: 'https://example.com'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        java-package: jdk
        architecture: x64

    - name: Ensure gradlew is executable
      run: |
        if [ -f "./gradlew" ]; then
          chmod +x gradlew
        else
          echo "gradlew not found!"
          exit 1
        fi

    - name: Replace URL in MainActivity
      run: |
        cd app/src/main/java/com/example/myapp
        if [ -f "MainActivity.java" ]; then
          sed -i "s|PLACEHOLDER_URL|${{ github.event.inputs.url }}|g" MainActivity.java
        else
          echo "MainActivity.java not found!"
          exit 1
        fi
        cd ../../../../../../../

    - name: Set up signing configuration
      run: |
        echo "KEYSTORE_PATH=${{ secrets.KEYSTORE_PATH }}" >> $GITHUB_ENV
        echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
        echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
        echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

    - name: Build signed APK
      run: ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: Output download URL
      run: |
        echo "Download URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts"
